import React, { useEffect } from 'react';
import Head from 'next/head';
import Header from './Header';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../app/store';
import { setStoredRecipes } from '../slicers/recipesSlicer';
import { recipe } from '../types/recipe';

const Layout = ({ children }: { children: JSX.Element }) => {
  const myRecipes: recipe[] = useSelector(
    (state: RootState) => state.recipes.value
  );
  const dispatch = useDispatch();
  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Remove recipes from localStorage for debugging purposes:
      // localStorage.removeItem('recipes');
      const storedRecipes = localStorage.getItem('recipes');
      if (storedRecipes?.length) {
        dispatch(setStoredRecipes(JSON.parse(storedRecipes)));
      }
    }
  }, []);

  if (typeof window !== 'undefined') {
    window.onunload = function () {
      if (myRecipes.length > 0) {
        localStorage.removeItem('recipes');
        const savingRecipes = JSON.stringify(myRecipes);
        localStorage.setItem('recipes', savingRecipes);
      }
    };
  }
  return (
    <div className='w-screen min-h-screen bg-yellow'>
      <Head>
        <title>My recipe book</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='p-4 mb-4'>{children}</main>
      <footer className='bg-orange h-12 flex justify-center items-center fixed bottom-0 w-full'>
        <span>
          Made by{' '}
          <a
            href='https://github.com/aledeloss'
            target='_blank'
            rel='noreferrer'
          >
            Ale Delos
          </a>
        </span>
      </footer>
    </div>
  );
};

export default Layout;
